import os
NOWPAYMENTS_API_BASE = "https://api.nowpayments.io/v1"


NOWPAYMENTS_API_KEY = os.getenv("NOWPAYMENTS_API_KEY", "R11FQJJ-2BWM7A5-PFYJ7K4-MW67BKQ")
NOWPAYMENTS_PUBLIC_KEY = os.getenv("NOWPAYMENTS_PUBLIC_KEY", "N7c4c8500-9093-4ec3-91d8-6143ed19641c")
NOWPAYMENTS_IPN_SECRET = os.getenv("NOWPAYMENTS_IPN_SECRET", "C+VMFxPiwz6LdB/enA2CAQOZ2qPDs6gH")
NOWPAYMENTS_AUTH_TOKEN = os.getenv("NOWPAYMENTS_AUTH_TOKEN", "")
NOWPAYMENTS_LOGIN_EMAIL = os.getenv("NOWPAYMENTS_LOGIN_EMAIL", "chikipikipinus@proton.me")
NOWPAYMENTS_LOGIN_PASSWORD = os.getenv("NOWPAYMENTS_LOGIN_PASSWORD", "Mamka228")
DEBUG_IPN = os.getenv("NOWPAYMENTS_IPN_DEBUG", "1")
